version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: art_scraper
    volumes:
      - ./images:/app/images 
      - ./:/app  
    environment:
      - PYTHONUNBUFFERED=1 
    restart: "no"
